### ISSUE TITLE
Stopped working in latest Home Assistant update - UPDATE: ISSUE IS WITH PETKIT'S SERVER, NOT THIS CODE

### ISSUE THREAD

**Issue by sclinton13** [hasscc/petkit#17]
I updated to HASS to core-2022.4.6 today and this custom component stopped working.

**Comment by katiuskt** [comment]
Same problem here but not sure if it is related with HASS update or with Petkit itself (cloud servers?).

In my case state is becoming unavailable or offline almost all the time. For a few minutes it becomes "feeding" (even if it is not feeding).

When it is unavailable I can see this in logs:

`Request Petkit api failed: ['GET', 'http://api.petkt.com/latest/discovery/device_roster', None, ContentTypeError(RequestInfo(url=URL('http://api.petkt.com/latest/discovery/device_roster'), method='GET', headers=<CIMultiDictProxy('Host': 'api.petkt.com', 'User-Agent': 'okhttp/3.12.1', 'X-Api-Version': '7.29.1', 'X-Client': 'Android(7.1.1;Xiaomi)', 'X-Session': 'XXXREDACTEDXXX', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>, real_url=URL('http://api.petkt.com/latest/discovery/device_roster')), (), message='Attempt to decode JSON with unexpected mimetype: ', headers=<CIMultiDictProxy('Content-Length': '0', 'Connection': 'keep-alive')>), 503, <StreamReader eof>]`

So it reports `Got petkit devices for MY REDACTED E-MAIL failed: {}`

Being said that, I have no clue how to try to get it working again :-(

**Comment by chumbazoid** [comment]
FWIW, am also having connectivity issues with my Petkit Mini since 3PM PDT 4/20/2022 (yesterday). Upgraded Home Assistant from 2022.4.5 to 2022.4.6 at 7PM yesterday. Reverted HA to 2022.4.5 after seeing OP but no change to Petkit status.

Device has been mostly offline/unavailable for the last ~24 hours (although still apparently connected to my wifi), intermittently returning to proper functionality for brief periods. Seeing a few reports of issues on reddit r/petkit as well, although surprisingly nothing on Twitter yet.

My gut sense is that this a Petkit server issue. Same issue in HA logs as per comment above:

> 2022-04-21 13:21:00 ERROR (MainThread) [custom_components.petkit] Request Petkit api failed: ['GET', 'http://api.petkt.com/latest/discovery/device_roster', None, ContentTypeError(RequestInfo(url=URL('http://api.petkt.com/latest/discovery/device_roster'), method='GET', headers=<CIMultiDictProxy('Host': 'api.petkt.com', 'User-Agent': 'okhttp/3.12.1', 'X-Api-Version': '7.29.1', 'X-Client': 'Android(7.1.1;Xiaomi)', 'X-Session': 'REDACTED', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>, real_url=URL('http://api.petkt.com/latest/discovery/device_roster')), (), message='Attempt to decode JSON with unexpected mimetype: ', headers=<CIMultiDictProxy('Content-Length': '0', 'Connection': 'keep-alive')>), 503, <StreamReader eof>]
> 2022-04-21 13:21:00 WARNING (MainThread) [custom_components.petkit] Got petkit devices for [REDACTED] failed: {}

**Comment by sclinton13** [comment]
Yeah, I posted here first, this might be all them. I logged out and cannot log back in. I am doing PCAPs now, to see if I can see what's what.

**Comment by sclinton13** [comment]
Seems it is them, response from server (http://api.petkt.com/latest/t3/dev_state_report):

Hypertext Transfer Protocol
HTTP/1.1 503 Service Unavailable: Back-end server is at capacity\r\n
[Expert Info (Chat/Sequence): HTTP/1.1 503 Service Unavailable: Back-end server is at capacity\r\n]
[HTTP/1.1 503 Service Unavailable: Back-end server is at capacity\r\n]
[Severity level: Chat]
[Group: Sequence]
Response Version: HTTP/1.1
Status Code: 503
[Status Code Description: Service Unavailable]
Response Phrase: Service Unavailable: Back-end server is at capacitv

**Comment by katiuskt** [comment]
Integration reports device "online" mostly of the time by now but still not able to feed from it.

Error message is reported: `ERROR (MainThread) [custom_components.petkit] Petkit feeding failed: {'error': {'code': 1, 'msg': '系统繁忙，请稍后重试'}}`

Which translated to english by DeepL means: `ERROR (MainThread) [custom_components.petkit] Petkit feeding failed: {'error': {'code': 1, 'msg': 'System busy，please try again later'}}`

Is it possible they've changed the way to interact with the device thorugh api.petkt.com or it is a genuine problem at server side? I ask because it sounds a little bit weird they still have problems in server side after a couple of days

**Comment by sclinton13** [comment]
I have it periodically losing connectivity via HASS and PetKit app, so they are still struggling with whatever happened.

**Comment by sclinton13** [comment]
Issues were all related to an extended server issue, code is woking great!

**Comment by holman** [comment]
fwiw, I'm trying to set it up for the first time and still continually get a `系统繁忙，请稍后重试` error in logs.

**Comment by sclinton13** [comment]
![6D1AB302-703B-47C8-9140-7550606061C0](https://user-images.githubusercontent.com/52946520/165160427-fa8a6d60-502b-4526-a8da-18c7fb84b2a4.jpeg)

**Comment by sclinton13** [comment]
Working for me as of 3:30PM EDT

**Comment by holman** [comment]
Maybe it's because I never was able to log in for a first time. When booting the server I get a:

> Got petkit device records for poop cauldron failed: {'error': {'code': 1, 'msg': '系统繁忙，请稍后重试'}}

Have a Pura Max; maybe it's also an issue of using that new hardware?
